server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka
  
eureka:
  instance:
    hostname: eureka
  server:
    renewal-percent-threshold: 0.85
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/